# -*- coding: utf-8 -*-
"""Data type.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CqPdJ7KXBjFDtO2oGUWJLnRyB-1pG0xh
"""

#1. Write a program to add two lists index-wise.
# Create a new list that contains the 0th index item from both the list, then the 1st index item,
# and so on till the last element. any leftover items will get added at the end of the new list.
list1 = ["M", "na", "i", "Ra"]
list2 = ["y", "me", "s", "hul"]
result=[]
for i in range(len(list1)):
    result.append([list1[i],list2[i]])
print(result)

#2. Write a program to add item 7000 after 6000 in the following Python List

list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].append(7000)
print(list1)

#3. Suppose you are given a list of candy and another list of same size representing no of items of respective candy.
#i.e -Write a program to show no. of items of each candy type.
candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]
for candy,count in zip(candy_list,no_of_items):
    print(f"{candy},{count}")

#4. Running Sum on list Write a program to print a list after performing running sum on it.
list1 = [1,2,3,4,5,6]
running_sum=[]
total=0
for num in list1:
    total+=num
    running_sum.append(total)
print(running_sum)

#5. You are given a list of integers. You are asked to make a list by running through elements of the list by adding all elements greater and itself.
#i.e. Say given list is [2,4,6,10,1] resultant list will be [22,20,10,23].
#For 1st element 2 ->> these are greater (4+6+10) values and 2 itself so on adding becomes 22.
#For 2nd element 4 ->> greater elements are (6, 10) and 4 itself, so on adding 20
#like wise for all other elememts.
#[2,4,6,10,1]-->[22,20,16,10,23]
list1=[2,4,6,10,1]
result=[]
for i in range(len(list1)):
    total=0
    for j in range(len(list1)):
        if list1[j] >= list1[i]:
            total += list1[j]
    result.append(total)
print(result)

#6. Find list of common unique items from two list. and show in increasing order

num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]
unique_item=[]
for i in num1:
    if i in num2 and i not in unique_item:
       unique_item.append(i)
       unique_item.sort()
print(unique_item)

#7. Sort a list of alphanumeric strings based on product value of numeric character in it.
# If in any string there is no numeric character take it's product value as 1.
string=['1ac21', '23fg', '456', '098d','1','kls']
def product_of_digit(s):
    product=1
    has_digit=False
    for i in s:
      if i.isdigit():
        product*=int(i)
        has_digit=True
    if not has_digit:
     product=1
    return product
sorted_string=sorted(string,key=product_of_digit)
print(sorted_string)

def numeric_value(s):
    digits = ''.join([c for c in s if c.isdigit()])
    if digits == '':
        return 1
    else:
        return int(digits)

string_list = ['1ac21', '23fg', '456', '098d', '1', 'kls']
sorted_list = sorted(string_list, key=numeric_value, reverse=True)

print(sorted_list)

#8. Write a program that can find the max number of each row of a matrix
#Example:
list1=[[1,2,3],[4,5,6],[7,8,9]]
row_max=[]
for row in list1:
 row_max.append(max(row))

print (row_max)

#9. Shortlist Students for a Job role Ask user to input students record and store in tuples for each record.
# Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.
Students=[]
n =int(input("enter number of students:"))
for i in range(n):
  print(f"\nEnter details of students{i+1}")
  name=input("Name: ")
  skill =input("primary Skill")
  education =input("higher Education:")
  year=int(input("year of gratuation:"))
  Students.append((name,skill,education,year))
print("\nEnter job Requirements:")
req_skill=input("primary skill")
req_education=input("higher education")
req_year=int(input("year of graduation"))

print("\nlist of student:")
found=False
for student in Students:
   if (student[1].lower() == req_skill.lower() and
      student[2].lower() == req_education.lower() and
      student[3] == req_year):

        print(f"Name: {student[0]}, Skill: {student[1]}, Education: {student[2]}, Year: {student[3]}")
        found = True

if not found:
    print("No matching students found.")

#10. Write a program to find set of common elements in three lists using sets.
ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]
common_element=set(ar1)& set(ar2)& set(ar3)
print(common_element)

#11. Write a program to count unique number of vowels using sets in a given string.
# Lowercase and upercase vowels will be taken as different.
string="hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
vowel="aeiouAEIOU"
count=0
for ch in vowel:
    if ch in string :
        count+=1
print("no of unique  vowel=",count)

string = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
vowel = "aeiouAEIOU"

unique_vowels = {ch for ch in string if ch in vowel}

print("Unique vowels:", unique_vowels)
print("Number of unique vowels =", len(unique_vowels))

#12. Intersection of two lists.
# Intersection of two list means we need to take all those elements which are common to both of
# the initial lists and store them into another list.
# Only use using list-comprehension.

lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
intersection = lst1 & lst2

print(intersection)

lst1 = [15, 9, 10, 56, 23, 78, 5, 4, 9]
lst2 = [9, 4, 5, 36, 47, 26, 10, 45, 87]

intersection = [x for x in lst1 if x in lst2]

print("Intersection:", intersection)

#13. Convert a list of Tuples into Dictionary.
list_of_tuple=[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]

dict_of_tuple=dict(list_of_tuple)
print(dict_of_tuple)

list_tuple=[('A', 1), ('B', 2), ('C', 3)]
dict_tuple=dict(list_tuple)
print(dict_tuple)

#14. Write a Python function that takes a list and returns a new list with unique elements of the first list.
list1=[1,2,3,3,3,3,4,5]
unique_element=set(list1)
print(unique_element)

def unique(list1):
  return list(set(list1))
list1=[1,2,3,3,3,3,4,5]
result=unique(list1)
print(result)

#15.  Write a Python program to print the even numbers from a given list.
list1=[1, 2, 3, 4, 5, 6, 7, 8, 9]
even=[]
for num in list1:
    if num%2==0:
        even.append(num)
print(even)

#16. Write a Python function to check whether a number is perfect or not.¶
#A Perfect number is a number that is half the sum of all of its positive divisors (including itself).
def is_perfect(n):
  sum_div=0
  for i in range(1,n):
    if n%i ==0:
      sum_div +=i
  return sum_div ==n
num=int(input("enter the number:"))
if is_perfect(num):
  print(num,"is a perfect number")
else:
  print(num,"is not a perfect number")

#17. Write a Python function to concatenate any no of dictionaries to create a new one.
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
result={**dic1,**dic2,**dic3}
print(result)

#18. Write a python function that receives a list of integers and prints out a histogram of bin size 10
list1=[13,42,15,37,22,39,41,50]
def histogram(list1):
  bins={}
  for num in list1:
    bin_range=(num//10)*10
    if bin_range not in bins:
      bins[bin_range]=0
    bins[bin_range]+=1
  for b in sorted(bins):
      print(f"{b}--{b+9}:{'*' * bins[b]}")
histogram(list1)