# -*- coding: utf-8 -*-
"""ExceptionHandling1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BkknKe3Kf6Wtiz1Q70xMrTvdLCdRmm2K
"""

#1. Write a Python program to handle a ZeroDivisionError exception when dividing a number by zero.
try:
    num1=int(input("enter the number:"))
    num2=int(input("enter the number :"))
    result=num1/num2
except ZeroDivisionError:
    print("Error,Not divided by zero")
else:
    print("Result",result)



#2. Write a Python program that prompts the user to input an integer and raises a ValueError exception if the input is not a valid integer.
try:
    num1=int(input("enter the number"))
    num2=int(input("enter the number"))
    result=num1/num2
    print(result)
except ValueError:
    print("Error,Invalid input,please enter the integer number>")



try:
    num =int(input("Enter an integer:"))
    print("You entered:",num)
except ValueError:
    print("Error:Please enter a valid integer!")

#3. Write a Python program that opens a file and handles a FileNotFoundError exception if the file does not exist.
try:
    f=open('sample_1.txt','r')
    f.read()
    f.close()
except FileNotFoundError :
    print("error: File not Found")

try:
    with open("sample_1.txt",'r') as f:
        print(f.read())

except FileNotFoundError :
    print("Error:File not Found")

#4. Write a Python program that prompts the user to input two numbers and raises a TypeError exception
# if the inputs are not numerical.
try:
    num1 = int(input("Enter first number: "))
    num2 = int(input("Enter second number: "))
    print("Sum:", num1 + num2)

except ValueError:
    raise TypeError("Inputs must be numerical")

#5. Write a Python program that opens a file and handles a PermissionError exception if there is a permission issue.
try:
    with open ("sample-1.txt",'r') as f:
        print(f.read())
except PermissionError :
    print("Error,there is permission issue." )

#6. Write a Python program that executes an operation on a list and handles an IndexError exception if the index is out of range.
try:
    list1=[1,2,56,34]
    index =int(input("enter index:"))

    print(list1[index])
except IndexError:
    print("Index out of range")

#7. Write a Python program that executes division and handles an ArithmeticError exception if there is an arithmetic error.
try:
    num1=int(input("enter the number"))
    num2=int(input("enter the number"))
    result=num1/num2
    print(result)
except ArithmeticError :
    print("Arithmetic error occured")

