# -*- coding: utf-8 -*-
"""fileassignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QPKbL5WmE79Vikb78IB7Za2_mGH4G7QN
"""

#1. Write a Python program to read an entire text file.
f=open("file.txt","r")
print(f.read())
f.close()

with open("file.txt","w") as file:
  file.write("Hello, \n")
  file.write("world")

#2. Write a Python program to read first n lines of a file.
try:
  n=int(input("enter the number of lines to read:"))
  with open("file.txt","r") as file:
    count=0
    for i in range(n):
      line=file.readline()
      if not line:
        print("\nfile has fewer lines than requested")
        break
      print(line,end="")
      count+=1
except FileNotFoundError:
  print("File not found")
except ValueError:
  print("please,enter the valid input")

#3. Write a Python program to append text to a file and display the text.
with open("file.txt","a") as file:
  file.write("Python\n")
with open("file.txt","r") as file:
  print(file.read())

#4. Write a Python program to read last n lines of a file.
try:
  n=int(input("enter the number of lines to read end:"))
  with open("file.txt","r") as file:
    lines=file.readlines()
    for line in lines[-n:]:
      print(line,end="")
except FileNotFoundError:
  print("File not found")
except ValueError:
  print("please,enter the valid input")

#5. Write a Python program to read a file line by line and store it into a list.
list1=[]
with open("file.txt","r") as file:
  for line in file:
    list1.append(line)
print(list1)

#6. Write a Python program to read a file line by line store it into a variable.
variable=""
with open("file.txt","r") as file:
  for line in file:
    variable+=line
print(variable)

with open("file.txt","r") as file:
  variable=file.read()
  print(variable)

#7. Write a python program to find the longest words.

with open("file.txt","r") as file:
  words=file.read().split()
  longest_word=max(words,key=len)
  print(longest_word)

#8. Write a Python program to count the number of lines in a text file.
with open("file.txt","r") as file:
  count=0
  for line in file:

      count+=1
  print(count)

#9. Write a Python program to count the frequency of words in a file.
with open("file.txt","r") as file:
  freq={}
  for ch in file:
    if ch in freq:
      freq[ch]+=1
    else:
      freq[ch]=1
  print(freq)

with open("file.txt","r") as file:
  words=file.read().split()
  freq={}
  for word in words:
    if word in freq:
      freq[word]+=1
    else:
      freq[word]=1
  print(freq)

#10. Write a Python program to get the file size of a plain file.
import os
size=os.path.getsize("file.txt")
print("file size",size,"bytes")

#11. Write a Python program to write a list to a file.
list1=["Apple","Banana","Mango"]
with open("file.txt","w") as file:
  for fruits in list1:
    file.write(fruits+"\n")

with open("file.txt","r")as file:
  print(file.read())

#12. Write a Python program to copy the contents of a file to another file .
with open("file.txt","r") as file:
  with open("source.txt","w")as source:
    data=file.read()
    source.write(data)
  print("filed copy successfully!")

with open("source.txt","r")as source:
 print(source.read())

#13. Write a Python program to read a random line from a file.
import random
with open("source.txt","r") as source:
  lines =source.readlines()
  random_line=random.choice(lines)
  print(random_line)

#14. Write a Python program to assess if a file is closed or not.
file=open("file.txt","r")
print("file is closed",file.closed)
file.close()
print("file is closed",file.closed)

with open("file.txt","r") as file:
  print("file is closed",file.closed)
print("file is close",file.closed)

#15.Write a Python program that takes a text file as input and returns the number of words of a given text file
with open(input("enter the file")) as file:
  count=0
  word=file.read().split()
  for ch in word:
    count+=1
  print(count)

with open(input("enter the file")) as file:
  words=file.read().split()
  print("number of words:",len(words))