# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gs9zKw8GxOUMpL8i_huw-S2imSx5niK6
"""

#1. Write a Python function to find the maximum of three numbers.
def max_number():
    num=(10,20,30)
    print(max(num))
max_number()



##1. Write a Python function to find the maximum of three numbers.
def max__number():
    num=(10,40,50)
    maximum=num[0]
    for i in num:
        if i>maximum:
            maximum=i
    print(maximum)
max__number()

#2. Write a Python function to sum all the numbers in a list.
def sum_num():
    nums= (8, 2, 3, 0, 7)
    print(sum(nums))
sum_num()

def sum_list():
  nums= (8, 2, 3, 0, 7)
  count=0
  for i in nums:
    count+=i
  print(count)
sum_list()

##3. Write a Python function to multiply all the numbers in a list.
def multiply_list(numbers):
    result=1
    for num in numbers:
        result*=num
    return result
list1=(8, 2, 3, -1, 7)
print("Multiplication of list:",multiply_list(list1))

#4. Write a Python function to reverse a string.
def reverse_string():
    string="1234abcd"
    print(string[::-1])
reverse_string()

#4. Write a Python function to reverse a string.
def reverse_strings():
    string="1234abcd"
    reverse=""
    for ch in string:
        reverse=ch+reverse
    print(reverse)
reverse_strings()

#5. Write a Python function to check whether a number falls within a given range.
def number_range(num,start,end):
    if num >= start and num <= end:
        print("number in the range")
    else:
        print("number is not range")
number_range(5,1,10)

#6Write a Python function that accepts a string and counts the number of upper and lower case letters.
def count_letter():
    string='The quick Brow Fox'
    lower_count=0
    upper_count=0
    for ch in string:
        if  ch.islower():
            lower_count+=1
        elif ch.isupper():
            upper_count+=1
    print("No. of Upper case characters", upper_count)
    print("No. of Lower case Characters", lower_count)
count_letter()

#7. Write a Python function that takes a list and returns a new list with distinct elements from the first list.
def distinct_element():
    list1=[1,2,3,3,3,3,4,5]
    return list(set(list1))

distinct_element()

#8. Write a Python function that checks whether a passed string is a palindrome or not.
def palindrome():
    string="nurses run"
    clean = string.replace(" ", "").lower()
    if string==string[::-1]:
        print("string is palindrome")
    else:
        print("string is not palindrome")
palindrome()

def palindrome():
 string="madam"
 if string == string[::-1]:
    print("string is palindrome")
 else:
    print("string is not palindrome")
palindrome()

#9. Write a Python program that accepts a hyphen-separated sequence of words as input and
# prints the words in a hyphen-separated sequence after sorting them alphabetically.

def alphabetical():
    sequence="green-red-yellow-black-white"
    words=sequence.split('-')
    words.sort()
    result='-'.join(words)
    print(result)
alphabetical()

#10. Write a Python program to detect the number of local variables declared in a function.
def local_variable():
    a=10
    b=20
    c=a+b
print ("Number of local variable:",local_variable.__code__.co_nlocals)

##11. Write a Python program to create a lambda function that adds 15 to a given number passed in as an argument,
# also create a lambda function that multiplies argument x with argument y and prints the result.
add_15=lambda  x:x+15
multiply=lambda x,y:x*y
print(add_15(10))
print(multiply(6,8))

#12. Write a Python program to create a function that takes one argument,
# and that argument will be multiplied with an unknown given number.
#Sample Output:
#Double the number of 15 = 30
#Triple the number of 15 = 45
	#Quadruple the number of 15 = 60
	#Quintuple the number 15 = 75

def multiplier(n):
    return lambda x:x*n
double=multiplier(2)
triple=multiplier(3)
quadruple=multiplier(4)
queintuple=multiplier(5)

num=15
print("Double the number of 15:",double(num))
print("triple the number of 15:",triple(num))
print("quadruple the number of 15:",quadruple(num))
print("queintuple the number of 15:",queintuple(num))

##13. Write a Python program to sort a list of tuples using Lambda.

subject=[('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
subject.sort(key=lambda x:x[1] )
print(subject)

#14. Write a Python program to sort a list of dictionaries using Lambda.

dict1=[{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}]
dict1.sort(key=lambda x:int(x['model']),reverse=True)
print(dict1)

#15. Write a Python program to filter a list of integers using Lambda.

list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even=list(filter(lambda x:x%2==0,list1))
odd=list(filter(lambda x:x%2!=0,list1))
print("Even number in the list",even)
print("odd number in the list",odd)



#16. Write a Python program to square and cube every number in a given list of integers using Lambda.

list1=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
square=list(map(lambda x:x**2,list1))
cube=list(map(lambda x:x**3,list1))
print("quare every number of the said list:",square)
print("Cube every number of the said list",cube)

#18. Write a Python program to find if a given string starts with a given character using Lambda.
string = "Hello"
given_char = "H"

start_with = lambda x: x and x[0] == given_char

if start_with(string):
    print("True")
else:
     print("False")

#19. Write a Python program to rearrange positive and negative numbers in a given array using Lambda.
list1 = [-1, 2, -3, 5, 7, 8, 9, -10]
positive=list(filter(lambda x:x>0,list1 ))
negative=list(filter(lambda x:x<0,list1))
negative.reverse()
result1=positive+negative
print(result1)

#20. Write a Python program to count the even and odd numbers in a given array of integers using Lambda.

list1 = [1, 2, 3, 5, 7, 8, 9, 10]

even_count = len(list(filter(lambda x: x % 2 == 0, list1)))
odd_count = len(list(filter(lambda x: x % 2 != 0, list1)))

print("Number of even numbers in the above array:",even_count)
print("Number of odd numbers in the above array:",odd_count)

#21. Write a Python program to find numbers divisible by nineteen or thirteen from a list of numbers using Lambda.
list1=[19, 65, 57, 39, 152, 639, 121, 44, 90, 190]
result1=list(filter(lambda x:x%19==0 or x%13==0,list1))

print(result1)

#22. Write a Python program to check whether a given string contains a capital letter,
# a lower case letter, a number and a minimum length using lambda.
string="disha2007"
upper_letter=any(map(lambda x: x.isupper(), string))
lower_letter=any(map(lambda x:x.islower(),string))
digit= any(map(lambda x: x.isdigit() ,string))
min_length=len(string)>=8

if upper_letter and lower_letter and digit and min_length:
    print("valid string")
else:
    print("Invalid string")