# -*- coding: utf-8 -*-
"""Challenges.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWcr4o0wcMSjIQmOQ3-RbvfwqOfeA8h3
"""

#1.Challenge: Student Marks Analyzer
students={}
n=int(input("Enter number of students"))
for i in range(n):
  name=input("enter the student name:")

  if name in students:
    print("Name alredy exist!Try again")
    continue
  marks=int(input("enter the marks"))
  students[name]=marks
print("\n-----Student report-------")
total_students=len(students)
print("total students:",total_students)
avg =sum(students.values())/total_students
print("Average Marks:",avg)
max_marks =max(students.values())
top_students =[name for name ,m in students.items()if m==max_marks]
print("Highest Marks:",max_marks)
print("top student(s):",",".join(top_students))

min_marks=min(students.values())
low_students = [name for name ,m in students.items()if m==min_marks]
print("lowest marks:",min_marks)
print("lowest student(s):",",".join(low_students))

#2Challenge: Student Marks Analyzer
import csv
import os
if not os.path.exists("contacts.csv"):
  with open("contacts.csv","w",newline="") as file:
    writer =csv.writer(file)
    writer.writerow(["Name","Phone","Email"])
def add_contact():
    name = input("Enter name:")
    phone =input("Enter phone number:")
    email =input("Enter email:")
    with open("contacts.csv","a",newline="")as file:
      writer =csv.writer(file)
      writer.writerow([name,phone,email])
    print("contact added successfully")
def view_contacts():
    with open("contacts.csv","r")as file:
      reader =csv.reader(file)
      print("\n ----contact list----")
      for row in reader:
        print(f"{row[0]:15}{row[1]:15}{row[2]}")
def search_contact():
    search =input("Enter name to search:")
    found=False
    with open("contacts.csv","r")as file:
      reader =csv.reader(file)
      for row in reader:
        if row and search in row[0].lower():
          print(f"{row[0]}-{row[1]}-{row[2]}")
          found=True
    if not found:
     print("contact not found")
while True:
  print("\n1 add contact")
  print("2.view contacts")
  print("3.search contact")
  print("4.exist")

  choice =input("Enter choice:")
  if choice =="1":
    add_contact()
  elif choice =="2":
    view_contacts()
  elif choice =="3":
    search_contact()
  elif choice =="4":
    print("existing...")
    break
  else:
    print("invalid choice")

#3 Challenge:  Personal Movie Tracker with JSON
import json
import os
file_name="movie.json"
def load_movie():
  if not os.path.exists(file_name):
    return[]
  with open(file_name,"r")as file:
    try:
      return json.load(file)
    except json.JSONDecodeError:
      return []

def save_movie(movies):
    with open(file_name,"w") as file:
      json.dump(movies,file,indent=4)
def add_movie():
    movies =load_movie()
    title =input("enter movie title:").strip().lower()
    genre =input("enter genre:").strip()
    rating=input("enter rating:").strip()
    movie={
        "title":title,
        "genre":genre,
        "rating":rating
    }
    movies.append(movie)
    save_movie(movies)
    print("movie added successfully")
def view_movie():
  movies =load_movie()

  if not movies:
    print("no movies found")
    return
  print("\nMovie list:")
  for i, movie in enumerate(movies, start=1):
        print(f"{i}. {movie['title']} | {movie['genre']} | {movie['rating']}")
def menu():
  while True:
    print("\n.--Movie Tracker---")
    print("1.add movie")
    print("2.view movie")
    print("3.exist")

    choice =input("enter choice:")
    if choice =="1":
      add_movie()
    elif choice=="2":
      view_movie()

    elif choice=="3":
      print("existing...")
      break
    else:
      print("invalid choice")
menu()



#4  Challenge: Real-Time Weather Logger (API + CSV)
import requests
import csv
import os
from datetime import datetime
API_KEY="afffdda0d48637fcab0c94c830bbb209"
FILE_NAME="weather_log.csv"


def get_weather(city):
  url =f"https://api.openweathermap.org/data/2.5/weather?q=Pune&appid={API_KEY}&units=metric"

  try:
    response=requests.get(url)
    data =response.json()

    if data.get("cod") != 200:
      return None

    return {
        "city":city,
        "temp":data["main"]["temp"],
        "condition":data["weather"][0]["main"]

    }
  except:
    return None

def save_weather(data):
  today =datetime.now().strftime("%Y-%m-%d")
  file_exists = os.path.exists(FILE_NAME)

  if file_exists:
    with open(FILE_NAME,"r")as file:
      reader =csv.reader(file)
      for row in reader:
        if row and row[0]==today and row[1]==data["city"]:
          print("already logged today for this city")
          return
  with open(FILE_NAME,"a",newline="")as file:
    writer =csv.writer(file)

    if not file_exists:
      writer.writerow(["Date", "City", "Temperature", "Condition"])

    writer.writerow([
        today,
        data["city"],
        data["temp"],
        data["condition"]
    ])

    print("weather logged successfully")
def view_logs():
    if not os.path.exists(FILE_NAME):
        print("No data found")
        return

    with open(FILE_NAME, "r") as file:
      print(file.read())

def analytics():
    if not os.path.exists(FILE_NAME):
        print("No data found")
        return

    temps = []
    conditions = []

    with open(FILE_NAME, "r") as file:
        reader = csv.DictReader(file)

        for row in reader:
            temps.append(float(row["Temperature"]))
            conditions.append(row["Condition"])
    if len(temps) == 0:
        print("No data for analytics")
        return

    print("\n--- ANALYTICS ---")
    print("Average Temp:", sum(temps)/len(temps))
    print("Max Temp:", max(temps))
    print("Min Temp:", min(temps))
    print("Most Frequent Condition:", max(set(conditions), key=conditions.count))

def main():
    while True:
        print("\n1. Add Weather Log")
        print("2. View Logs")
        print("3. Analytics")
        print("4. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            city = input("Enter city: ")
            data = get_weather(city)

            if data:
                save_weather(data)
            else:
                print("Invalid city or API error")

        elif choice == "2":
            view_logs()

        elif choice == "3":
            analytics()

        elif choice == "4":
            break

        else:
            print("Invalid choice")

if __name__ == "__main__":
    main()

import os

file_name = "weather_log.csv"

if os.path.exists(file_name):
    os.remove(file_name)
    print("File deleted successfully")
else:
    print("File not found")